front-end/components/AgeScreen/AgeScreen.js
=> Add Header to Age Screen

front-end/components/PrepScanningScreen/PrepScanningScreen.js, front-end/package.json
=> Add Prepare scanning screen

front-end/components/common/HeaderWithLogo.js
This will close #30 
Example screenshot:
=> Add Header With Logo component

front-end/components/common/Product.js
This will close #33 
Example usage:
<Product
productName={'Neutrogena Hydro Boost Water Gel'}
productImgPath={require('../../assets/images/product-1.jpg')}
category={{ name: 'Skincare (face)', color: '#4396DC' }}
rating={3.4}
productAddHandle={() => {}}
/>
Cannot send screenshots taken from Joe phone so have to take low res pic instead:
=> Frontend add product component

front-end/components/SkinColorScreen/SkinColorScreen.js, front-end/components/SkinColorScreen/SkinColorScreenContainer.js
=> Frontend skin color screen

front-end/actions/types.js, front-end/actions/userInput.js, front-end/components/AgeScreen/AgeScreenContainer.js, front-end/components/GenderScreen/GenderScreen.js, front-end/components/GenderScreen/GenderScreenContainer.js, front-end/components/LocationScreen/LocationScreen.js, front-end/components/LocationScreen/LocationScreenContainer.js, front-end/components/SkinColorScreen/SkinColorScreenContainer.js, front-end/components/SkinTypeScreen/SkinTypeScreen.js, front-end/components/SkinTypeScreen/SkinTypeScreenContainer.js, front-end/components/UserInputScreens/UserInputScreens.js, front-end/components/UserInputScreens/UserInputScreensContainer.js, front-end/components/common/Header.js, front-end/reducers/index.js, front-end/reducers/userInputReducer.js, front-end/utils/colorCode.js, front-end/utils/styles.js
This will close #47 
Screenshots are similar to the one in Figma design:
=> Combine user input screens

front-end/components/ScanningResultScreen/ScanningResultScreen.js, front-end/components/ScanningResultScreen/ScanningResultScreenContainer.js, front-end/components/common/OverallScore.js, front-end/components/common/SkinConditionResult.js, front-end/utils/colorCode.js
This will close #56  
Usage:
```
<OverallScore
score=86.5
scoreTag='moderate'
scoreTagColor={colorCode.moderateTag}
lightVersion=false
displayRow=true
/>
```
`lightVersion` and `displayRow` is use for rendering overall score in homepage screens
```
<SkinConditionResult
moistureScore=50
dirtScore=50
uvScore=50
pigmentScore=50
recommendText='Recommendation text here'
/>
```
=> Create scanning result components and alter scanning result screen

front-end/components/common/RecordCard.js
Usage:
```
<RecordCard
gradientBackground={colorCode.moderateGradient}
score={86.5}
scoreTag={'moderate'}
scoreTagColor={colorCode.moderateTag}
lightVersion={true}
displayRow={false}
recommendText={'Recommend text here'}
/>
```
This will close #61
=> Create Record Card Component

front-end/components/RecordDetailModal/RecordDetailContainer.js, front-end/components/RecordDetailModal/RecordDetailModal.js, front-end/utils/colorCode.js
=> Create Record Detail Modal and Container

front-end/components/HomepageScreen/HomepageScreen1.js, front-end/components/HomepageScreen/HomepageScreen1Container.js
=> Create Homepage Screen 1

front-end/components/HomepageScreen/HomepageScreen2.js, front-end/components/HomepageScreen/HomepageScreen2Container.js, front-end/components/common/RecordCard.js, front-end/package.json
This will close #65
Remember to run `npm install` after merging this commit
=> Add initial structure for Homepage Screen 2

front-end/components/ProfileComponent/ProfileComponent.js, front-end/components/ProfileComponent/ProfileComponentContainer.js
=> Create Profile Component

front-end/components/HomepageScreen/HomepageScreen2.js, front-end/components/HomepageScreen/HomepageScreen2Container.js, front-end/components/common/RecordCard.js
=> Create Homepage Screen 2 and Make Button Interactive

front-end/components/HomepageScreen/HomepageScreen2.js, front-end/components/HomepageScreen/HomepageScreen2Container.js, front-end/components/common/EmptyCard.js, front-end/components/common/RecordCard.js, front-end/utils/colorCode.js
=> Add Frontend Delete Card Handle and Animation - Add Empty Card Handle

front-end/components/HomepageScreen/HomepageScreen1.js, front-end/components/HomepageScreen/HomepageScreen1Container.js, front-end/components/common/RecordCard.js
=> Make Homepage Screen 1 Search Bar Interactive (Turning search input to score tag)

front-end/components/FriendsComponent/FriendsComponent.js, front-end/components/FriendsComponent/FriendsComponentContainer.js
=> Add Friends Component

back-end/index.js, back-end/package.json, back-end/routers/auth/index.js, back-end/utils/knex_config.js
=> Add API for signup

back-end/package.json, back-end/routers/auth/index.js, back-end/utils/env_config.json, back-end/utils/middlewares.js
=> Add API for signin

back-end/models/brand.js, back-end/routers/api/doc.md, back-end/routers/api/index.js
=> Add API for fetching brands

back-end/models/category.js, back-end/routers/api/doc.md, back-end/routers/api/index.js
=> Add API for fetching categories

back-end/models/product.js, back-end/routers/api/doc.md, back-end/routers/api/index.js
=> Add API for fetching product's detail

back-end/models/product.js, back-end/models/review.js, back-end/routers/api/index.js
=> Add api fetching product reviews

back-end/models/user.js
=> Add API for fetching other user's reviews

back-end/models/user.js, back-end/routers/api/index.js
=> Add api fetching my profile

back-end/models/record.js, back-end/models/user.js, back-end/routers/api/index.js
=> Add API for fetching user's records

back-end/models/user.js
=> Add API for fetching user's favorite products

back-end/routers/api/index.js, back-end/utils/index.js
=> Add api add favorite product to user

back-end/routers/api/index.js
=> Add API to upload user info

back-end/models/category.js, back-end/models/product.js, back-end/models/record.js, back-end/models/review.js, back-end/models/user.js
=> Fetch products by category

front-end/components/PrepScanningScreen/PrepScanningScreen.js, front-end/components/PrepScanningScreen/PrepScanningScreenContainer.js, front-end/components/ScanningProcessScreens/ScanningProcessScreens.js, front-end/components/ScanningProcessScreens/ScanningProcessScreensContainer.js, front-end/components/ScanningScreen/ScanningScreenContainer.js, front-end/utils/colorCode.js
=> Combine scanning screens together

front-end/App.js, front-end/components/LoginScreen/LoginScreen.js, front-end/components/LoginScreen/LoginScreenContainer.js, front-end/components/ScanningProcessScreens/ScanningProcessScreens.js, front-end/components/ScanningProcessScreens/ScanningProcessScreensContainer.js, front-end/components/ScanningResultScreen/ScanningResultScreen.js, front-end/components/ScanningResultScreen/ScanningResultScreenContainer.js, front-end/components/UserInputScreens/UserInputScreens.js, front-end/components/UserInputScreens/UserInputScreensContainer.js
=> Connect Login + Scanning + User Input Screens together

front-end/components/UserInputScreens/UserInputScreensContainer.js
=> Connect Recommendation Screen to user flow

back-end/models/user.js
=> Add skin condition to api

front-end/components/ScanningProcessScreens/ScanningProcessScreensContainer.js, front-end/components/UserInputScreens/UserInputScreensContainer.js
=> Add logic change from scanning to user input screen

front-end/actions/record.js, front-end/actions/types.js
=> Add ability to post scanning result (record) to db

back-end/models/record.js, back-end/models/user.js, back-end/routers/api/index.js, front-end/actions/record.js, front-end/actions/types.js, front-end/actions/user_input.js, front-end/components/HomepageScreen/HomepageScreen1Container.js, front-end/components/HomepageScreen/HomepageScreen2Container.js, front-end/components/common/RecordCard.js, front-end/reducers/index.js, front-end/reducers/recordReducer.js, front-end/utils/index.js
=> Fetch real data for record card

front-end/components/HomepageScreen/HomepageScreen2Container.js, front-end/components/RecordDetailModal/RecordDetailContainer.js
This will:
- Close #137 
- Close #139
=> Fetch real data for Record Card Detail

front-end/App.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreen.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreenContainer.js
=> Frontend product dtb screen

front-end/actions/category.js, front-end/actions/types.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreen.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreenContainer.js, front-end/components/common/Product.js, front-end/reducers/categoryReducer.js, front-end/reducers/index.js
This will:
- Close #165 
- Close #162
=> Connect Product List screen + fetch real data

front-end/components/ProductDatabaseScreen/ProductCategoryScreenContainer.js, front-end/utils/colorCode.js
=> Create Product Category Screen

front-end/App.js, front-end/components/StatisticsScreen/Graph.js, front-end/package.json
=> Create Graph Component Styling

front-end/components/StatisticsScreen/StatisticsScreen.js, front-end/components/StatisticsScreen/StatisticsScreenContainer.js, front-end/components/common/OverallScore.js
This will:
- Close #163 
- Close #160
=> Create Statistics Screen

front-end/App.js, front-end/components/ProductDatabaseScreen/ProductCategoryScreenContainer.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreen.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreenContainer.js, front-end/components/common/Product.js, front-end/utils/index.js
=> Connect category list to product list

front-end/actions/homepage1.js, front-end/actions/types.js, front-end/components/HomepageScreen/HomepageScreen1.js, front-end/components/HomepageScreen/HomepageScreen1Container.js, front-end/components/HomepageScreen/HomepageScreen2Container.js, front-end/reducers/homepage1Reducer.js, front-end/reducers/index.js
=> Make tag filter work

front-end/components/ProductDatabaseScreen/ProductDatabaseScreen.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreenContainer.js
=> Make filter product work

front-end/components/common/Loader.js, front-end/components/common/LoaderContainer.js
=> Create Loading Screen

front-end/components/HomepageScreen/HomepageScreen1.js, front-end/components/HomepageScreen/HomepageScreen1Container.js, front-end/components/HomepageScreen/HomepageScreen2.js, front-end/components/common/RecordCard.js
=> Change from Homepage2 from clicking Record Card

front-end/components/ProfileComponent/ProfileComponent.js
=> Fix alignment of variables in profile component

front-end/components/ProductDetail/ProductDetail.js, front-end/components/ProductDetailReviews/ProductDetailReviews.js
=> Fix TopReview margins (remove Flex option)

front-end/components/HomepageScreen/HomepageScreen1.js, front-end/components/HomepageScreen/HomepageScreen1Container.js
Solution is not display any card at all if the tag doesnt match any of the available ones
This will close #193
=> Fix tag filter

front-end/components/ProfileComponent/ProfileComponent.js
=> Change skin condition badge color dynamically

back-end/routers/api/index.js
=> Add API remove favorite product

front-end/actions/product.js, front-end/actions/record.js, front-end/components/HomepageScreen/HomepageScreen1Container.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreen.js, front-end/components/ProductDatabaseScreen/ProductDatabaseScreenContainer.js, front-end/components/common/OperationIndicator.js
=> Make Add/Remove Products from Favorite Products work in Product List

front-end/components/ScanningResultScreen/ScanningResultScreenContainer.js, front-end/components/common/OverallScore.js, front-end/components/common/SkinConditionResult.js
=> Randomize scanning result

front-end/components/GetStartedScreen/GetStartedScreen.js, front-end/components/GetStartedScreen/GetStartedScreenContainer.js
=> Create Get Started Screen

front-end/App.js, front-end/components/LoginScreen/LoginScreen.js, front-end/package.json
=> Create Login Screen Animation Transition

recommendation_service/app.py, recommendation_service/recommendation_model.py
=> Add server for recommendation service

recommendation_service/Dockerfile, recommendation_service/requirements.txt
=> Add docker file to deploy recommendation service

back-end/routers/api/index.js
=> Add API to fetch recommendation products

front-end/components/ProductDetail/ProductDetail.js
Show the text: "No reviews yet, .."
This will close #227
=> Fix error when there's no review

back-end/routers/api/index.js
=> Add API to delete record

front-end/actions/record.js, front-end/components/ScanningResultScreen/ScanningResultScreenContainer.js
=> Save scanning result to database
